### PR TITLE
Calendar multiday (and all day) events fix.

### LINKED ISSUE #418: BUG: Multiday events on the calendar not showing up on the events page.
I tried to add a multiday event to the calendar so that folks can see the devedmonton hackathon but it's not quite showing up as expected.

The google calendar and the https://devedmonton.com/api/events shown here.
image

The event doesn't seem to show up 
image

I know @keifererikson might know a little bit about this.

As a temporary measure I'll just make three separate events here :)

Note references: https://github.com/devedmonton/DES-Website/issues/312

### PR DESCRIPTION
**Pull request by charrde**
## What issue is this referencing?

This PR fixes #418 

## Do these code changes work locally and have you tested that they fix the issue yourself?

-   [x] yes!

## Does the following command run without warnings or errors?

-   [x] yes! `npm run pr-checks`

## Have you taken a look at our [contributing guidelines](https://github.com/devedmonton/DES-Website/blob/main/.github/CONTRIBUTING.md)?

-   [x] yes!

## My node version matches the one suggested when running `nvm use`?

-   [x] yes!

Screenshot 2024-10-17 185554
Screenshot 2024-10-17 185645

### CODE REVIEW

**Review by arashsheyda — APPROVED** [review]

File: pages/events.vue [hunk 1]
```diff
@@ -35,8 +35,8 @@ function renderMarkdown(description: string) {
 
 const createEventsList = (events: any) => {
   return events.map((event: any) => new Event(
-    event.start.dateTime,
-    event.end.dateTime,
+    event.start.dateTime || event.start.date,
+    event.end.dateTime || event.end.date,
```
Comment (dgmouris) [inline pages/events.vue:39]: Yep, that looks awesome! Thanks @charrde I'm going to merge a bit later today so that we can observe the deployment together.

**Review by MandyMeindersma — APPROVED** [review]

**Review by dgmouris — APPROVED** [review]

**Comment by dgmouris** [comment]
@charrde we'll merge this which is awesome but a few things here

1. it would be awesome is removing the time from the display.
2. Note the times seem to be offset a little bit 5pm-5pm we can fix this in a future PR as well.

**Comment by dgmouris** [comment]
Merging we're going to fix this wierd date thing later, I would like to have the meetups up so that I can see them and we can fix it later.
